### ISSUE TITLE
Définition de composants avec "host"

### ISSUE THREAD

**Issue by Valenrieu** [denis-migdal/LISS#1]
Erreur de typage lors de la définition de composants avec le paramètre host. Exemple qui produit une erreur :

```typescript
class RegisteredUsers extends LISS({host: HTMLParagraphElement}) {
    constructor() {
        super();
    }
}

LISS.define("registered-users", RegisteredUsers);
```

**Comment by denis-migdal** [comment]
Issue non reproduite avec `tsc` version 4.9.3, mais bien reproduite avec nouvelle version 5.3.3 ....
